In [1]:
import numpy as np
import pandas as pd

In [2]:
batsman_pd = pd.read_excel("6655876402143_batsman_round1 (3).xlsx")
bowlers_pd = pd.read_excel("6655876ef0ec2_bowler_round1 (3).xlsx")
match_pd = pd.read_excel("6655877834f04_matchlevel_round1 (3).xlsx")

Removing Duplicates

In [3]:
def removing_duplicates(df,id_columns: list, sort_by = 'timestamp'):
    df=df.sort_values(by=sort_by,ascending=False)
    df=df.drop_duplicates(subset=id_columns,keep='first')
    return df

In [4]:
print(f'Original value count = {len(batsman_pd)}')
batsman_df=removing_duplicates(batsman_pd,list(batsman_pd.drop(columns = 'ingestion_timestamp').columns),'ingestion_timestamp')
print(f'New value count = {len(batsman_df)}')

Original value count = 24925
New value count = 24877

In [5]:
print(f'Original value count = {len(bowlers_pd)}')
bowler_df=removing_duplicates(bowlers_pd,list(bowlers_pd.drop(columns = 'ingestion_timestamp').columns),'ingestion_timestamp')
print(f'New value count = {len(bowler_df)}')

Original value count = 18911
New value count = 18861

In [6]:
print(f'Original value count = {len(match_pd)}')
match_df=removing_duplicates(match_pd,list(match_pd.drop(columns = 'ingestion_timestamp').columns),'ingestion_timestamp')
print(f'New value count = {len(match_df)}')

Original value count = 1738
New value count = 1688

In [7]:

batsman_df['Fours'] = pd.to_numeric(batsman_df['Fours'], errors='coerce')
batsman_df['Fours'] = batsman_df['Fours'].round().astype('Int64')
batsman_df['runs'] = batsman_df['runs'].astype('Int64')
batsman_df['Sixes'] = pd.to_numeric(batsman_df['Sixes'], errors='coerce').round().astype('Int64')

'''batsman_df['batsman_dob'] = batsman_df['batsman_dob'].replace('0000-00-00', None)
batsman_df['batsman_dob'] = pd.to_datetime(batsman_df['batsman_dob'], format='mixed', dayfirst=False)
batsman_df['bowler_dob'] = batsman_df['bowler_dob'].replace('0000-00-00', None)
batsman_df['bowler_dob'] = pd.to_datetime(batsman_df['bowler_dob'], format='mixed', dayfirst=False)'''

"batsman_df['batsman_dob'] = batsman_df['batsman_dob'].replace('0000-00-00', None)\nbatsman_df['batsman_dob'] = pd.to_datetime(batsman_df['batsman_dob'], format='mixed', dayfirst=False)\nbatsman_df['bowler_dob'] = batsman_df['bowler_dob'].replace('0000-00-00', None)\nbatsman_df['bowler_dob'] = pd.to_datetime(batsman_df['bowler_dob'], format='mixed', dayfirst=False)"

In [8]:
batsman_df[batsman_df['runs'].isnull()]

,match id,batsman,batsman_id,batsman_dob,batsman_details,is_batsman_captain,is_batsman_keeper,inning,runs,balls_faced,...,bowler_id,bowler_dob,bowler_details,is_bowler_keeper,is_bowler_captain,strike_rate,Fours,Sixes,match_dt,ingestion_timestamp
13966,9856734,C Cr,4171460,1999-04-20,IRE:Right-hand bat:Right-arm medium-fast:,0,0,1,<NA>,6,...,2097017.0,1986-04-24,ZIM:Right-hand bat:Right-arm offbreak:,0.0,1.0,133.33,1,<NA>,2023-12-07,2024-03-26 03:41:36.000
15591,9702769,JP Is,4635658,1995-03-04,AUS:Right-hand bat:None:,0,1,1,<NA>,44,...,4393402.0,1994-03-03,AUS:Left-hand bat:Right-arm medium-fast:,0.0,0.0,145.45,3,4,2023-12-26,2024-03-26 03:41:36.000
14906,9680201,TL St,4381761,1994-12-14,NZ:Right-hand bat:None:,0,1,1,<NA>,23,...,8067002.0,2003-01-09,SL:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,78.26,<NA>,1,2023-08-04,2024-03-26 03:41:36.000
6846,9440556,MG Bl,2288789,1991-02-14,NZ:Left-hand bat:Right-arm offbreak:,0,0,1,<NA>,2,...,NaN,NaN,NaN,NaN,NaN,50.00,<NA>,<NA>,2023-01-27,2024-03-26 03:41:36.000
10662,9433472,AZ Ls,3225305,1993-04-14,ENG:Left-hand bat:Legbreak:,1,0,1,<NA>,13,...,3673914.0,1993-04-18,ENG:Right-hand bat:Right-arm medium-fast:,0.0,0.0,100.00,2,<NA>,2023-06-09,2024-03-26 03:41:36.000
10879,9433325,T Ke,3294444,1994-08-19,ENG:Right-hand bat:Right-arm offbreak:,0,1,1,<NA>,10,...,3030733.0,1989-02-10,SA:Right-hand bat:Right-arm offbreak:,0.0,1.0,170.00,2,1,2023-06-04,2024-03-26 03:41:36.000
10786,9680166,DM de Sa,3260564,1991-09-06,SL:Right-hand bat:Right-arm offbreak:,0,0,2,<NA>,31,...,3061225.0,1991-09-09,SL:Right-hand bat:Right-arm medium:,0.0,1.0,138.71,5,1,2023-07-31,2024-03-26 03:41:36.000
8977,9457524,Ar Ha,2815728,1991-08-15,AFG:Right-hand bat:Slow left-arm orthodox:,0,0,2,<NA>,1,...,8106629.0,2003-02-15,PAK:Right-hand bat:Right-arm fast:,0.0,0.0,0.00,<NA>,<NA>,2023-01-23,2024-03-26 03:41:36.000
22359,9433836,JM En,7810977,2001-11-14,ENG:Right-hand bat:Right-arm medium:,0,0,2,<NA>,24,...,3546297.0,1991-12-14,NZ:Right-hand bat:Right-arm fast-medium:,0.0,0.0,191.67,6,2,2023-07-02,2024-03-26 03:41:36.000
23111,9516625,YK Jl,8058959,2001-12-28,IND:Left-hand bat:Legbreak:,0,0,1,<NA>,62,...,8713270.0,1997-12-20,IND:Left-hand bat:Left-arm medium:,0.0,0.0,200.00,16,8,2023-04-30,2024-03-26 03:41:36.000
21214,9713199,Sn Gl,7491224,1999-09-08,IND:Right-hand bat:Right-arm offbreak:,0,0,1,<NA>,2,...,2659222.0,1993-10-01,SA:Left-hand bat:Right-arm medium-fast:,0.0,0.0,0.00,<NA>,<NA>,2023-12-12,2024-03-26 03:41:36.000
22194,9849755,SR Ba,7753605,1998-09-24,KENYA:Right-hand bat:Right-arm medium:,0,0,2,<NA>,23,...,8059379.0,1990-04-15,UGA:Right-hand bat:Right-arm medium-fast:,0.0,0.0,117.39,1,1,2023-11-29,2024-03-26 03:41:36.000
24790,9644109,A Sa,9059000,2004-12-03,UAE:Right-hand bat:None:,0,1,2,<NA>,3,...,1626561.0,1988-12-11,NZ:Right-hand bat:Right-arm medium-fast:,0.0,1.0,0.00,<NA>,<NA>,2023-08-19,2024-03-26 03:41:36.000
23604,9516520,Ht Br,8180500,1995-09-16,IND:Left-hand bat:Slow left-arm orthodox:,0,0,2,<NA>,13,...,6586824.0,1994-03-13,IND:Right-hand bat:Right-arm fast:,0.0,0.0,100.00,1,<NA>,2023-04-20,2024-03-26 03:41:36.000
16713,9516373,S De,5001170,1993-06-26,IND:Left-hand bat:Right-arm medium:,0,0,1,<NA>,16,...,8228100.0,2000-09-05,IND:Right-hand bat:Legbreak googly:,0.0,0.0,168.75,1,3,2023-04-03,2024-03-26 03:41:36.000
2890,9484593,BJ Cg,1612610,1987-01-30,AUS:Right-hand bat:Right-arm fast-medium:,0,0,2,<NA>,13,...,5736016.0,2000-03-24,AFG:Right-hand bat:Right-arm medium-fast:,0.0,0.0,115.38,1,1,2023-03-01,2024-03-26 03:41:36.000
4888,9684534,MK Py,2034423,1989-09-10,IND:Right-hand bat:Right-arm medium:,0,0,1,<NA>,17,...,9455557.0,2003-05-15,IND:Right-hand bat:Legbreak googly:,0.0,0.0,100.00,<NA>,1,2023-10-21,2024-03-26 03:41:36.000
13972,9262021,D Jn,4171691,2000-05-01,SA:Right-hand bat:Left-arm fast:,0,0,2,<NA>,8,...,4239794.0,1995-03-24,SA:Right-hand bat:Right-arm fast-medium:,0.0,0.0,100.00,1,<NA>,2022-08-31,2023-03-10 21:21:02.995
12691,9076822,Tn Ad,3769555,1995-04-03,BAN:Left-hand bat:Right-arm fast:,0,0,1,<NA>,5,...,392888.0,1995-01-05,BAN:Right-hand bat:Right-arm medium:,0.0,0.0,40.00,<NA>,<NA>,2022-01-22,2023-03-10 21:21:02.995
12909,9076920,Mk Hn,3850944,1995-12-10,BAN:Right-hand bat:Right-arm offbreak:,1,0,1,<NA>,30,...,6493346.0,1992-09-20,BAN:Right-hand bat:Right-arm medium:,0.0,0.0,113.33,3,2,2022-02-03,2023-03-10 21:21:02.995
16745,9051244,Kl Sh,5017144,1995-02-07,PAK:Left-hand bat:Slow left-arm orthodox:,0,0,2,<NA>,23,...,8131255.0,1993-11-07,PAK:Right-hand bat:Right-arm fast:,0.0,0.0,139.13,4,1,2022-02-27,2023-03-10 21:21:02.995
19267,9225362,OC My,6347494,1997-01-04,WI:Left-hand bat:Left-arm fast-medium:,0,0,2,<NA>,3,...,8228100.0,2000-09-05,IND:Right-hand bat:Legbreak googly:,0.0,0.0,0.00,<NA>,<NA>,2022-08-07,2023-03-10 21:21:02.995
1897,9271730,AS Fr,363047,1987-11-28,WI:Right-hand bat:Right-arm medium-fast:,0,1,1,<NA>,22,...,8067002.0,2003-01-09,SL:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,159.09,4,2,2022-12-14,2023-03-10 21:21:02.995
15187,9085327,DJ Lb,4460070,1995-09-07,ENG:Right-hand bat:Right-arm medium-fast:,0,0,2,<NA>,1,...,NaN,NaN,NaN,NaN,NaN,0.00,<NA>,<NA>,2022-06-24,2023-03-10 21:21:02.995
14631,9051027,Kn Gm,4365465,1995-10-10,PAK:Right-hand bat:Slow left-arm orthodox:,0,0,1,<NA>,31,...,2157770.0,1990-02-28,ENG:Left-hand bat:Left-arm fast-medium:,0.0,0.0,138.71,2,3,2022-01-29,2023-03-10 21:21:02.995
24398,9352230,An Al Kn,8688868,2005-11-15,UAE:Right-hand bat:Slow left-arm orthodox:,0,0,2,<NA>,17,...,6930286.0,2001-06-03,BAN:Left-hand bat:Left-arm medium-fast:,0.0,0.0,147.06,3,<NA>,2022-09-25,2023-03-10 21:21:02.995
22883,9077011,Pz Hn En,7976590,2002-06-12,BAN:Left-hand bat:None:,0,0,1,<NA>,7,...,5831622.0,1994-12-12,BAN:Right-hand bat:Right-arm offbreak:,0.0,0.0,100.00,<NA>,1,2022-02-12,2023-03-10 21:21:02.995
7653,9051069,Un Qr,2437077,1993-08-10,PAK:Left-hand bat:Legbreak:,0,0,2,<NA>,2,...,NaN,NaN,NaN,NaN,NaN,350.00,<NA>,1,2022-02-02,2023-03-10 21:21:02.995
385,9084956,SJ Ct,82228,1984-10-11,ENG:Right-hand bat:Right-arm offbreak:,0,0,1,<NA>,24,...,5367676.0,1996-10-09,ENG:Left-hand bat:Right-arm medium-fast:,0.0,0.0,170.83,2,3,2022-06-08,2023-03-10 21:21:02.995
10864,9084956,T Ke,3294444,1994-08-19,ENG:Right-hand bat:Right-arm offbreak:,0,1,2,<NA>,43,...,8055417.0,1999-05-03,ENG:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,179.07,9,4,2022-06-08,2023-03-10 21:21:02.995
9891,9271744,MD Sa,3061225,1991-09-09,SL:Right-hand bat:Right-arm medium:,1,0,1,<NA>,5,...,2270519.0,1986-10-19,SL:Right-hand bat:Right-arm fast-medium:,0.0,0.0,240.00,1,1,2022-12-17,2023-03-10 21:21:02.995
23983,8638055,JA Fd,8354821,2000-12-19,NZ:Right-hand bat:Right-arm medium-fast:,0,0,1,<NA>,2,...,4949790.0,1993-05-20,NZ:Right-hand bat:Right-arm offbreak:,0.0,0.0,50.00,<NA>,<NA>,2021-01-04,2022-03-22 12:43:21.000
192,8587998,SJ Oe,49496,1984-12-09,AUS:Right-hand bat:Slow left-arm orthodox:,0,0,2,<NA>,4,...,4967738.0,1995-04-08,AUS:Right-hand bat:Right-arm fast-medium:,0.0,0.0,0.00,<NA>,<NA>,2021-01-10,2022-03-22 12:43:21.000
77,8637824,AJ Fh,37351,1986-11-17,AUS:Right-hand bat:Slow left-arm orthodox:,1,0,1,<NA>,44,...,3913475.0,1992-10-31,NZ:Right-hand bat:Legbreak:,0.0,0.0,156.82,8,2,2021-03-03,2022-03-22 12:43:21.000
23501,8638174,WT Ol,8144184,1997-09-29,NZ:Right-hand bat:Right-arm offbreak:,0,0,1,<NA>,30,...,2236086.0,1986-06-11,NZ:Left-hand bat:Left-arm fast-medium:,0.0,0.0,133.33,2,2,2021-02-01,2022-03-22 12:43:21.000
20162,9038434,KA Ba,6710850,1998-11-23,SL:Right-hand bat:Legbreak:,0,0,1,<NA>,30,...,1636627.0,1989-08-14,SL:Right-hand bat:Right-arm offbreak:,0.0,0.0,140.00,3,1,2021-12-10,2022-03-22 12:43:21.000
23322,8710771,St Kr,8118151,1995-12-12,IND:Right-hand bat:Right-arm medium-fast:,0,0,1,<NA>,10,...,NaN,NaN,NaN,NaN,NaN,210.00,3,1,2021-01-19,2022-03-22 12:43:21.000
9799,8647722,H Kn,3057312,1991-07-30,SA:Right-hand bat:Right-arm offbreak:,1,1,2,<NA>,40,...,NaN,NaN,NaN,NaN,NaN,135.00,3,3,2021-02-19,2022-03-22 12:43:21.000
9488,8778692,SV Sn,2981614,1994-11-11,IND:Right-hand bat:None:,1,1,2,<NA>,53,...,NaN,NaN,NaN,NaN,NaN,132.08,8,1,2021-09-25,2022-03-22 12:43:21.000
9960,8916284,SJ Bd,3065502,1992-04-29,NAM:Right-hand bat:Right-arm medium-fast:,0,0,1,<NA>,21,...,1642738.0,1988-12-06,IND:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,100.00,1,1,2021-11-08,2022-03-22 12:43:21.000
9437,8710288,RG Me,2969546,1992-02-02,IND:Right-hand bat:Right-arm medium:,0,0,1,<NA>,6,...,NaN,NaN,NaN,NaN,NaN,150.00,<NA>,1,2021-01-12,2022-03-22 12:43:21.000
7068,8588208,AI Rs,2335381,1992-04-17,AUS:Right-hand bat:Right-arm offbreak:,0,0,1,<NA>,11,...,4132295.0,1993-10-04,AUS:Right-hand bat:Legbreak:,0.0,0.0,81.82,<NA>,<NA>,2021-01-31,2022-03-22 12:43:21.000
5592,8763691,A Be,2123974,1990-12-28,IRE:Right-hand bat:Right-arm offbreak:,1,0,2,<NA>,7,...,2659502.0,1990-06-08,SA:Left-hand bat:Left-arm fast-medium:,0.0,0.0,85.71,1,<NA>,2021-07-22,2022-03-22 12:43:21.000
6033,8752169,SG Bk,2173646,1990-04-19,ENG:Left-hand bat:Legbreak:,0,0,1,<NA>,15,...,65183.0,1985-02-28,ENG:Right-hand bat:Right-arm medium-fast:,0.0,0.0,120.00,1,1,2021-06-26,2022-03-22 12:43:21.000
7829,8752344,DL Ld,2531913,1992-06-15,ENG:Right-hand bat:Right-arm medium:,0,0,2,<NA>,29,...,NaN,NaN,NaN,0.0,NaN,175.86,7,1,2021-07-02,2022-03-22 12:43:21.000
2933,8768822,SP Ne,1613919,1988-05-26,WI:Left-hand bat:Right-arm offbreak:,0,0,1,<NA>,3,...,4420828.0,1996-05-26,ENG:Right-hand bat:Right-arm offbreak:,0.0,0.0,33.33,<NA>,<NA>,2021-08-08,2022-03-22 12:43:21.000
2802,8895872,MS We,1611364,1987-12-26,AUS:Left-hand bat:Right-arm medium:,1,1,2,<NA>,3,...,5831622.0,1994-12-12,BAN:Right-hand bat:Right-arm offbreak:,0.0,0.0,66.67,<NA>,<NA>,2021-08-07,2022-03-22 12:43:21.000
15108,8752351,SS Ei,4421689,1994-03-28,ENG:Right-hand bat:None:,0,0,2,<NA>,4,...,3252395.0,1994-04-10,ENG:Right-hand bat:Right-arm medium-fast:,0.0,1.0,100.00,1,<NA>,2021-07-02,2022-03-22 12:43:21.000
3746,8887486,AD Hs,1749075,1989-01-03,ENG:Right-hand bat:Right-arm medium:,0,0,2,<NA>,2,...,7353828.0,1998-12-17,AUS:Right-hand bat:Right-arm fast-medium:,0.0,0.0,0.00,<NA>,<NA>,2021-12-06,2022-03-22 12:43:21.000
14296,8895865,BR Mt,4223883,1994-12-12,AUS:Right-hand bat:Right-arm medium:,0,0,2,<NA>,41,...,393014.0,1987-03-24,BAN:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,85.37,<NA>,2,2021-08-06,2022-03-22 12:43:21.000

In [9]:
def calculate_runs(df):
    for index, row in df.iterrows():
        if pd.isnull(row['runs']):
            if not pd.isnull(row['strike_rate']) and not pd.isnull(row['balls_faced']) and row['balls_faced'] != 0:
                # Calculate runs using strike_rate and balls_faced
                calculated_runs = (row['strike_rate'] * row['balls_faced']) / 100
                df.at[index, 'runs'] = round(calculated_runs, 0)  # Round to the nearest integer explicitly
            elif row['strike_rate'] == 0:
                # Replace runs null value with 0 if strike_rate is 0
                df.at[index, 'runs'] = 0
    return df

In [10]:
batsman_df=calculate_runs(batsman_df)

In [11]:
batsman_df['runs'].max()

162

In [12]:
import pandas as pd

def calculate_strike_rate(df):
    for index, row in df.iterrows():
        if pd.isnull(row['strike_rate']):
            if not pd.isnull(row['runs']) and not pd.isnull(row['balls_faced']) and row['balls_faced'] != 0:
                # Calculate strike_rate using runs and balls_faced
                calculated_strike_rate = (row['runs'] / row['balls_faced']) * 100
                df.at[index, 'strike_rate'] = round(calculated_strike_rate, 2)  # Round to two decimal places explicitly
            elif row['runs'] == 0:
                # Replace strike_rate null value with 0 if runs is 0
                df.at[index, 'strike_rate'] = 0
    return df

In [13]:
batsman_df=calculate_strike_rate(batsman_df)

In [14]:
batsman_df['strike_rate'].max()

600.0

In [15]:
batsman_df.describe()

,match id,batsman_id,is_batsman_captain,is_batsman_keeper,inning,runs,balls_faced,over_faced_first,bowler_id,is_bowler_keeper,is_bowler_captain,strike_rate,Fours,Sixes
count,2.487700e+04,2.487700e+04,24877.000000,24877.000000,24877.000000,24877.0,24877.000000,24877.000000,1.836900e+04,18954.0,18369.000000,24877.000000,14353.0,9158.0
mean,9.100151e+06,4.102384e+06,0.113920,0.113961,1.486313,18.299674,14.129356,9.121253,4.332252e+06,0.0,0.056345,110.384269,2.745349,1.945512
std,3.133890e+05,2.421703e+06,0.317721,0.317770,0.499823,20.258225,12.766584,6.823539,2.362059e+06,0.0,0.230593,69.039563,2.165534,1.389905
min,8.587795e+06,3.146400e+04,0.000000,0.000000,1.000000,0.0,0.000000,-18.300000,3.406100e+04,0.0,0.000000,0.000000,1.0,1.0
25%,8.778818e+06,2.231928e+06,0.000000,0.000000,1.000000,3.0,4.000000,2.100000,2.537800e+06,0.0,0.000000,64.710000,1.0,1.0
50%,9.085047e+06,3.706065e+06,0.000000,0.000000,1.000000,11.0,10.000000,8.400000,3.882850e+06,0.0,0.000000,108.330000,2.0,1.0
75%,9.388448e+06,6.003584e+06,0.000000,0.000000,2.000000,27.0,20.000000,15.400000,6.347256e+06,0.0,0.000000,150.000000,4.0,2.0
max,9.887856e+06,9.899140e+06,1.000000,1.000000,2.000000,162.0,75.000000,20.900000,9.888584e+06,0.0,1.000000,600.000000,22.0,13.0

In [16]:
batsman_df.isnull()

,match id,batsman,batsman_id,batsman_dob,batsman_details,is_batsman_captain,is_batsman_keeper,inning,runs,balls_faced,...,bowler_id,bowler_dob,bowler_details,is_bowler_keeper,is_bowler_captain,strike_rate,Fours,Sixes,match_dt,ingestion_timestamp
12462,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,True,True,False,False
13124,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13116,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
13117,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,False,False,False,False
13118,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13852,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
13853,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
13856,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,True,True,False,False
13878,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,False,False,False,False,False
136,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False

In [17]:
batsman_df[batsman_df['Sixes'].isnull()]

,match id,batsman,batsman_id,batsman_dob,batsman_details,is_batsman_captain,is_batsman_keeper,inning,runs,balls_faced,...,bowler_id,bowler_dob,bowler_details,is_bowler_keeper,is_bowler_captain,strike_rate,Fours,Sixes,match_dt,ingestion_timestamp
12462,9684632,KS Bt,3706065,1993-10-03,IND:Right-hand bat:None:,1,1,1,1,2,...,NaN,NaT,NaN,NaN,NaN,50.00,<NA>,<NA>,2023-10-23,2024-03-26 03:41:36
13116,9516569,AR Pl,3882850,1994-01-20,IND:Left-hand bat:Slow left-arm orthodox:,0,0,1,34,34,...,2282125.0,1990-02-05,IND:Right-hand bat:Right-arm medium:,0.0,0.0,100.00,4,<NA>,2023-04-24,2024-03-26 03:41:36
13118,9516744,AR Pl,3882850,1994-01-20,IND:Left-hand bat:Slow left-arm orthodox:,0,0,2,1,2,...,7453697.0,1999-08-04,IND:Right-hand bat:Legbreak googly:,0.0,0.0,50.00,<NA>,<NA>,2023-05-13,2024-03-26 03:41:36
13122,9725750,AR Pl,3882850,1994-01-20,IND:Left-hand bat:Slow left-arm orthodox:,0,0,2,2,6,...,2790675.0,1992-02-29,AUS:Right-hand bat:Right-arm fast-medium:,0.0,0.0,33.33,<NA>,<NA>,2023-11-23,2024-03-26 03:41:36
13123,9725771,AR Pl,3882850,1994-01-20,IND:Left-hand bat:Slow left-arm orthodox:,0,0,1,0,1,...,4756982.0,1994-06-23,AUS:Left-hand bat:Left-arm fast-medium:,0.0,0.0,0.00,<NA>,<NA>,2023-12-01,2024-03-26 03:41:36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13851,8752512,BD Gr,4167946,1997-04-03,NED:Right-hand bat:Right-arm fast:,0,0,2,1,1,...,NaN,NaT,NaN,NaN,NaN,100.00,<NA>,<NA>,2021-07-18,2022-03-22 12:43:21
13852,8916011,BD Gr,4167946,1997-04-03,NED:Right-hand bat:Right-arm fast:,0,0,1,0,1,...,3685100.0,1996-03-27,IRE:Right-hand bat:Right-arm fast-medium:,0.0,0.0,0.00,<NA>,<NA>,2021-10-18,2022-03-22 12:43:21
13853,8916074,BD Gr,4167946,1997-04-03,NED:Right-hand bat:Right-arm fast:,0,0,1,0,2,...,5490638.0,1997-02-13,SL:Left-hand bat:Right-arm fast:,0.0,0.0,0.00,<NA>,<NA>,2021-10-22,2022-03-22 12:43:21
13856,8647624,O Ce,4169339,1997-07-09,SA:Right-hand bat:Right-arm fast:,0,0,2,1,2,...,NaN,NaT,NaN,NaN,NaN,50.00,<NA>,<NA>,2021-02-24,2022-03-22 12:43:21
136,8778510,MC Hs,41740,1987-02-01,AUS:Right-hand bat:Right-arm fast-medium:,0,0,1,14,17,...,7491294.0,2000-09-04,IND:Left-hand bat:Slow left-arm orthodox:,0.0,0.0,82.35,<NA>,<NA>,2021-04-21,2022-03-13 18:43:20

In [17]:
print(batsman_df)

       match id   batsman  batsman_id batsman_dob  \
12462   9684632     KS Bt     3706065  1993-10-03
13124   9725778     AR Pl     3882850  1994-01-20
13116   9516569     AR Pl     3882850  1994-01-20
13117   9516611     AR Pl     3882850  1994-01-20
13118   9516744     AR Pl     3882850  1994-01-20
...         ...       ...         ...         ...
13852   8916011     BD Gr     4167946  1997-04-03
13853   8916074     BD Gr     4167946  1997-04-03
13856   8647624      O Ce     4169339  1997-07-09
13878   8768808  JL du Py     4170186  1995-01-12
136     8778510     MC Hs       41740  1987-02-01

                                 batsman_details  is_batsman_captain  \
12462                   IND:Right-hand bat:None:                   1
13124  IND:Left-hand bat:Slow left-arm orthodox:                   0
13116  IND:Left-hand bat:Slow left-arm orthodox:                   0
13117  IND:Left-hand bat:Slow left-arm orthodox:                   0
13118  IND:Left-hand bat:Slow left-arm orthodox:                   0
...                                          ...                 ...
13852         NED:Right-hand bat:Right-arm fast:                   0
13853         NED:Right-hand bat:Right-arm fast:                   0
13856          SA:Right-hand bat:Right-arm fast:                   0
13878  ENG:Left-hand bat:Slow left-arm orthodox:                   0
136    AUS:Right-hand bat:Right-arm fast-medium:                   0

       is_batsman_keeper  inning  runs  balls_faced  ...  bowler_id  \
12462                  1       1     1            2  ...        NaN
13124                  0       1    31           21  ...  1907352.0
13116                  0       1    34           34  ...  2282125.0
13117                  0       2    29           14  ...        NaN
13118                  0       2     1            2  ...  7453697.0
...                  ...     ...   ...          ...  ...        ...
13852                  0       1     0            1  ...  3685100.0
13853                  0       1     0            2  ...  5490638.0
13856                  0       2     1            2  ...        NaN
13878                  0       1    30           22  ...        NaN
136                    0       1    14           17  ...  7491294.0

       bowler_dob                             bowler_details is_bowler_keeper  \
12462         NaN                                        NaN              NaN
13124  1990-04-20   AUS:Right-hand bat:Left-arm fast-medium:              0.0
13116  1990-02-05       IND:Right-hand bat:Right-arm medium:              0.0
13117         NaN                                        NaN              NaN
13118  1999-08-04        IND:Right-hand bat:Legbreak googly:              0.0
...           ...                                        ...              ...
13852  1996-03-27  IRE:Right-hand bat:Right-arm fast-medium:              0.0
13853  1997-02-13           SL:Left-hand bat:Right-arm fast:              0.0
13856         NaN                                        NaN              NaN
13878         NaN                                        NaN              NaN
136    2000-09-04  IND:Left-hand bat:Slow left-arm orthodox:              0.0

       is_bowler_captain strike_rate Fours  Sixes    match_dt  \
12462                NaN       50.00  <NA>   <NA>  2023-10-23
13124                0.0      147.62     2      1  2023-12-03
13116                0.0      100.00     4   <NA>  2023-04-24
13117                NaN      207.14     1      2  2023-04-29
13118                0.0       50.00  <NA>   <NA>  2023-05-13
...                  ...         ...   ...    ...         ...
13852                0.0        0.00  <NA>   <NA>  2021-10-18
13853                0.0        0.00  <NA>   <NA>  2021-10-22
13856                NaN       50.00  <NA>   <NA>  2021-02-24
13878                NaN      136.36     1      1  2021-08-06
136                  0.0       82.35  <NA>   <NA>  2021-04-21

       ingestion_timestamp
12462  2024-03-26 03:41:36
13124  2024-03-26 03:41:36
13116  2024-03-26 03:41:36
13117  2024-03-26 03:41:36
13118  2024-03-26 03:41:36
...                    ...
13852  2022-03-22 12:43:21
13853  2022-03-22 12:43:21
13856  2022-03-22 12:43:21
13878  2022-03-22 12:43:21
136    2022-03-13 18:43:20

[24877 rows x 24 columns]

In [18]:
null_values = batsman_df.isnull().sum()

In [19]:
null_values

match id                   0
batsman                    0
batsman_id                 0
batsman_dob                0
batsman_details            0
is_batsman_captain         0
is_batsman_keeper          0
inning                     0
runs                       0
balls_faced                0
over_faced_first           0
wicket kind             5462
out_by_bowler           5462
out_by_fielder             6
bowler_id               6508
bowler_dob              6508
bowler_details          6508
is_bowler_keeper        5923
is_bowler_captain       6508
strike_rate                0
Fours                  10524
Sixes                  15719
match_dt                   0
ingestion_timestamp        0
dtype: int64

Bowler table preprocessing

In [20]:
def fill_missing_runs(df):

  for index, row in df.iterrows():
    if pd.isnull(row['runs']):  # Check for null value in 'runs'
      # Ensure valid values for calculation (not null and balls_faced > 0)
      if not pd.isnull(row['economy']) and not pd.isnull(row['balls_bowled']) :
        # Calculate estimated runs using economy and overs bowled
        estimated_runs = (row['economy'] * (row['balls_bowled'] / 6))  
        df.at[index, 'runs'] = round(estimated_runs,0)
  return df

In [21]:
bowler_df=fill_missing_runs(bowler_df)

In [22]:
bowler_df['runs'].max()

82.0

In [23]:
bowler_df[bowler_df['economy'].isnull()]

,match id,bowler,bowler_id,bowler_dob,bowler_details,is_bowler_captain,is_bowler_keeper,inning,runs,wicket_count,balls_bowled,economy,maiden,dots,Fours,Sixes,wides,noballs,match_dt,ingestion_timestamp
11378,9587087,KA Pl,4739580,1998-02-21,WI:Right-hand bat:Right-arm fast-medium:,0,0,1,19.0,0,18,NaN,0,5,1,0,0,0,2023-09-13,2024-03-14 17:12:36.995
5908,9433591,JH Dy,2850868,1990-08-03,SCOT:Right-hand bat:Right-arm medium-fast:,0,0,1,31.0,0,18,NaN,0,3,3,1,0,1,2023-06-19,2024-03-14 17:12:36.995
7990,9440570,MJ Sr,3519011,1992-02-05,NZ:Left-hand bat:Slow left-arm orthodox:,1,0,1,37.0,0,24,NaN,0,5,4,1,0,0,2023-02-01,2024-03-14 17:12:36.995
13593,9433290,GS Sw,6005866,1998-02-10,ENG:Right-hand bat:Right-arm medium-fast:,0,0,2,33.0,1,24,NaN,0,10,4,1,0,1,2023-06-04,2024-03-14 17:12:36.995
12907,9457398,Km Jt,5554282,1998-08-11,AFG:Right-hand bat:Right-arm medium:,0,0,2,15.0,1,12,NaN,0,3,2,0,0,0,2023-01-07,2024-03-14 17:12:36.995
15482,9587024,RS Ps,7459647,1995-08-14,WI:Right-hand bat:Right-arm medium:,0,0,2,11.0,2,12,NaN,0,7,1,0,1,0,2023-09-02,2024-03-14 17:12:36.995
14508,9516499,Md Sj,6586824,1994-03-13,IND:Right-hand bat:Right-arm fast:,0,0,1,30.0,1,24,NaN,0,10,1,2,1,0,2023-04-17,2024-03-14 17:12:36.995
760,9484488,In Tr,284339,1979-03-27,SA:Right-hand bat:Legbreak googly:,0,0,1,40.0,1,24,NaN,0,4,2,2,1,0,2023-02-14,2024-03-14 17:12:36.995
1880,9433262,SP Ne,1613919,1988-05-26,WI:Left-hand bat:Right-arm offbreak:,0,0,2,16.0,1,24,NaN,0,12,1,0,0,0,2023-06-02,2024-03-14 17:12:36.995
3340,9587024,Sr Ra,2097017,1986-04-24,ZIM:Right-hand bat:Right-arm offbreak:,1,0,2,21.0,1,18,NaN,0,6,1,0,1,0,2023-09-02,2024-03-14 17:12:36.995
12490,8887822,N Mw,5497274,1993-07-14,AUS:Right-hand bat:Right-arm medium-fast:,0,0,1,30.0,2,18,NaN,0,4,5,0,0,0,2022-01-15,2023-03-27 19:21:06.000
12088,9085082,NA Sr,5231218,1992-10-12,ENG:Right-hand bat:Legbreak:,0,0,1,36.0,0,24,NaN,0,9,2,2,0,1,2022-06-17,2023-03-27 19:21:06.000
9577,9084683,L Wd,4012203,1995-08-02,ENG:Left-hand bat:Left-arm fast-medium:,0,0,2,24.0,1,24,NaN,0,13,2,0,0,0,2022-05-29,2023-03-27 19:21:06.000
13337,9084802,NT Es,5788418,1994-09-22,AUS:Right-hand bat:Right-arm fast-medium:,0,0,1,26.0,0,24,NaN,0,12,3,0,2,1,2022-06-02,2023-03-27 19:21:06.000
13285,9272437,DR Ss,5788320,1992-10-27,AUS:Right-hand bat:Left-arm fast-medium:,0,0,2,34.0,0,12,NaN,0,1,2,3,1,0,2022-12-20,2023-03-27 19:21:06.000
17131,9051076,Nm Sh,8106629,2003-02-15,PAK:Right-hand bat:Right-arm fast:,0,0,1,42.0,0,24,NaN,0,5,5,1,1,0,2022-02-03,2023-03-27 19:21:06.000
337,9085110,SJ My,125915,1986-11-19,ENG:Right-hand bat:Right-arm medium:,0,0,1,17.0,0,12,NaN,0,2,0,1,0,0,2022-06-17,2023-03-27 19:21:06.000
14104,9128608,M Ph Ka,6420126,1996-02-19,IND:Right-hand bat:Right-arm fast-medium:,0,0,2,23.0,2,24,NaN,0,16,2,1,3,0,2022-04-26,2023-03-27 19:21:06.000
13749,9084830,TH Dd,6249256,1996-03-16,AUS:Right-hand bat:Right-arm offbreak:,0,0,1,22.0,1,12,NaN,0,2,3,0,1,0,2022-06-03,2023-03-27 19:21:06.000
13899,9084851,OC My,6347494,1997-01-04,WI:Left-hand bat:Left-arm fast-medium:,0,0,1,30.0,4,24,NaN,0,9,4,0,3,0,2022-06-03,2023-03-27 19:21:06.000
15770,9262035,J Bp,7550864,2000-05-30,WI:Right-hand bat:Slow left-arm orthodox:,0,0,1,19.0,1,18,NaN,0,6,0,0,4,0,2022-09-01,2023-03-27 19:21:06.000
14820,9097101,S Le,6722540,2000-08-02,NEP:Right-hand bat:Legbreak googly:,1,0,1,13.0,3,24,NaN,0,16,0,1,0,0,2022-02-24,2023-03-27 19:21:06.000
15071,9076962,Sl Im,6930286,2001-06-03,BAN:Left-hand bat:Left-arm medium-fast:,0,0,2,28.0,2,24,NaN,0,11,3,1,0,0,2022-02-08,2023-03-27 19:21:06.000
6624,9262231,HR Wh,3102854,1992-04-23,WI:Left-hand bat:Legbreak googly:,0,0,2,25.0,1,16,NaN,0,7,2,2,0,0,2022-09-27,2023-03-27 19:21:06.000
4908,9123197,CA Yg,2550414,1990-04-04,IRE:Right-hand bat:Right-arm fast-medium:,0,0,1,18.0,0,18,NaN,0,9,2,0,0,0,2022-07-18,2023-03-27 19:21:06.000
4013,9331356,S Kl,2282132,1990-05-19,IND:Right-hand bat:Right-arm medium:,0,0,2,32.0,1,24,NaN,1,9,4,1,0,0,2022-11-01,2023-03-27 19:21:06.000
4333,9128685,S Gl,2412073,1993-09-04,IND:Right-hand bat:Legbreak:,0,0,1,34.0,1,18,NaN,0,7,1,4,0,0,2022-05-05,2023-03-27 19:21:06.000
4534,9087231,PA vn Mn,2436776,1993-01-15,NED:Right-hand bat:Right-arm fast-medium:,0,0,2,33.0,1,18,NaN,0,5,1,2,1,1,2022-11-06,2023-03-27 19:21:06.000
3011,9087042,JR Hd,2018001,1991-01-08,AUS:Left-hand bat:Right-arm fast-medium:,0,0,1,41.0,2,24,NaN,0,8,5,1,1,0,2022-10-22,2023-03-27 19:21:06.000
1062,8778545,DJ Bo,360086,1983-10-07,WI:Right-hand bat:Right-arm medium:,0,0,2,19.0,0,12,NaN,0,4,0,2,0,0,2021-04-25,2022-03-21 03:44:58.000
6097,8778734,R Ta,2966879,1993-05-20,IND:Left-hand bat:Legbreak:,0,0,2,23.0,0,18,NaN,0,4,3,0,0,0,2021-09-29,2022-03-21 03:44:58.000
15054,8873780,Sl Im,6930286,2001-06-03,BAN:Left-hand bat:Left-arm medium-fast:,0,0,1,33.0,3,24,NaN,0,10,2,2,2,0,2021-07-23,2022-03-21 03:44:58.000
6024,8816765,AR Me,2921680,1993-04-30,IRE:Left-hand bat:Right-arm offbreak:,1,0,1,20.0,1,24,NaN,0,11,2,0,NaN,0,2021-06-18,2022-03-21 03:44:58.000
5725,8588187,SA At,2790675,1992-02-29,AUS:Right-hand bat:Right-arm fast-medium:,0,0,2,33.0,2,18,NaN,0,3,3,1,0,0,2021-02-06,2022-03-21 03:44:58.000
9762,8961616,AS Rt,4141563,1993-12-04,IND:Right-hand bat:Right-arm medium:,0,0,1,26.0,0,24,NaN,0,8,3,0,0,0,2021-11-05,2022-03-21 03:44:58.000
18142,8729300,Af Jd,8425696,2000-10-10,PAK:Right-hand bat:Left-arm medium-fast:,0,0,1,50.0,1,24,NaN,0,11,2,6,0,0,2021-06-21,2022-03-21 03:44:58.000
276,8752330,SJ Ct,82228,1984-10-11,ENG:Right-hand bat:Right-arm offbreak:,0,0,1,26.0,0,18,NaN,0,7,3,1,1,0,2021-07-02,2022-03-21 03:44:58.000
8964,8778797,K Ra,3851518,1995-05-25,SA:Left-hand bat:Right-arm fast:,0,0,1,33.0,0,24,NaN,0,9,1,2,1,1,2021-10-02,2022-03-21 03:44:58.000
11810,8638167,JD Gn,4950224,1993-04-29,NZ:Right-hand bat:Right-arm medium-fast:,0,0,1,20.0,1,12,NaN,0,2,1,1,1,0,2021-01-31,2022-03-21 03:44:58.000
11893,8887514,Zr Kn,4985546,1998-12-20,AFG:Left-hand bat:Left-arm wrist-spin:,0,0,1,33.0,2,24,NaN,0,10,1,2,2,0,2021-12-09,2022-03-21 03:44:58.000
12699,8752246,Nq,5554142,1999-09-23,AFG:Right-hand bat:Right-arm medium-fast:,0,0,2,27.0,2,20,NaN,0,13,4,1,2,0,2021-06-29,2022-03-21 03:44:58.000
1643,8638195,HK Bt,1585464,1987-02-22,NZ:Left-hand bat:Right-arm medium-fast:,0,0,2,28.0,2,24,NaN,0,9,2,1,1,0,2021-02-07,2022-03-21 03:44:58.000
6566,8752155,LV vn Bk,3083667,1990-09-07,NED:Right-hand bat:Right-arm medium-fast:,0,0,1,36.0,2,18,NaN,0,7,6,1,2,0,2021-06-25,2022-03-21 03:44:58.000
14849,8887577,RP Mh,6732004,1996-06-21,AUS:Right-hand bat:Right-arm fast:,0,0,1,1.0,1,6,NaN,0,5,0,0,0,0,2021-12-20,2022-03-21 03:44:58.000
1449,8768773,LA Dn,1482998,1990-03-01,ENG:Right-hand bat:Slow left-arm orthodox:,0,0,2,13.0,0,10,NaN,0,3,1,0,0,0,2021-08-01,2022-03-21 03:44:58.000
7200,8752239,C On,3252395,1994-04-10,ENG:Right-hand bat:Right-arm medium-fast:,0,0,2,14.0,1,18,NaN,0,10,1,0,0,0,2021-06-29,2022-03-21 03:44:58.000
7202,8752351,C On,3252395,1994-04-10,ENG:Right-hand bat:Right-arm medium-fast:,1,0,2,28.0,3,24,NaN,0,13,3,1,0,1,2021-07-02,2022-03-21 03:44:58.000
6749,8778475,AF Me,3156033,1992-04-13,NZ:Right-hand bat:Right-arm fast:,0,0,2,33.0,0,18,NaN,0,4,1,3,1,0,2021-04-17,2022-03-21 03:44:58.000
2775,8916256,AD Rl,1934099,1988-04-29,WI:Right-hand bat:Right-arm fast:,0,0,2,25.0,0,12,NaN,0,1,3,1,0,0,2021-11-06,2022-03-21 03:44:58.000
13404,8800294,B Mi,5789370,1996-10-02,ZIM:Right-hand bat:Right-arm fast-medium:,0,0,1,22.0,1,24,NaN,0,10,1,0,1,0,2021-04-21,2022-03-21 03:44:58.000

In [24]:
def fill_missing_economy(df):
    for index, row in df.iterrows():
        if pd.isnull(row['economy']):  # Check for null value in 'economy'
            # Ensure valid values for calculation (not null and balls_bowled > 0)
            if not pd.isnull(row['runs']) and not pd.isnull(row['balls_bowled']) and row['balls_bowled'] > 0:
                # Calculate estimated economy using runs and overs bowled
                estimated_economy = row['runs'] / (row['balls_bowled'] / 6)
                df.at[index, 'economy'] = round(estimated_economy, 2)
    return df

In [25]:
bowler_df=fill_missing_economy(bowler_df)

In [26]:
bowler_df['economy'].max()

36.0

In [27]:
null_values1 = bowler_df.isnull().sum()

In [28]:
null_values1

match id                0
bowler                  0
bowler_id               0
bowler_dob              0
bowler_details          0
is_bowler_captain       0
is_bowler_keeper        0
inning                  0
runs                    0
wicket_count            0
balls_bowled            0
economy                 0
maiden                  0
dots                    2
Fours                   0
Sixes                   0
wides                  34
noballs                 0
match_dt                0
ingestion_timestamp     0
dtype: int64

In [29]:
null_values2 = match_df.isnull().sum()

In [30]:
null_values2

match id                 0
team1                    0
team2                    0
outcome                  0
winner                   0
by                      50
win amount               0
player of match        469
toss winner              0
toss decision            0
match type               0
venue                    0
city                   178
match_dt                 0
lighting                 0
series_name              0
season                   0
ground_id                0
umpire1                181
umpire2                181
inning1_runs             0
inning1_wickets          0
inning1_balls            0
inning2_runs             0
inning2_wickets          0
inning2_balls            0
team1_id                81
team1_roster_names       0
team1_roster_ids        81
team2_id                75
team2_roster_names       0
team2_roster_ids        75
ingestion_timestamp      0
dtype: int64

In [31]:
match_df

,match id,team1,team2,outcome,winner,by,win amount,player of match,toss winner,toss decision,...,inning2_runs,inning2_wickets,inning2_balls,team1_id,team1_roster_names,team1_roster_ids,team2_id,team2_roster_names,team2_roster_ids,ingestion_timestamp
1737,9887856,An,Ud Ab Es,normal,An,runs,72,Rh Gz,Ud Ab Es,field,...,131,4,120,293.0,Hh Zi:Rh Gz:Im Zn:Ah Oi:Md Ni:Nh Zn:Km Jt:Qs A...,5554212.0:6818622.0:6450576.0:5736016.0:181404...,202.0,Md Wm:Kd Sh:V Ad:S Ua:Bl Hd:T Si:Ai Nr:An Al K...,8688952.0:7990828.0:8250115.0:9899140.0:846378...,2024-02-25 06:12:58
1446,9433829,Ne,Le,normal,Le,wickets,6,NaN,Le,field,...,139,4,106,8917.0,R Vs:EN Gy:CA Ln:DJ Wy:SA Zb:J Bd:LD Ms:AJ Te:...,4873700.0:8040164.0:2286472.0:2157770.0:464530...,8182.0,PD St:JC Br:SJ Ct:LS Le:DJ Ml:DJ Vs:LP Ws:RP J...,4685568.0:2162782.0:82228.0:2827327.0:2672214....,2024-02-25 06:12:58
1434,9433696,Ex,He,normal,He,wickets,4,NaN,He,field,...,212,6,120,7258.0,DW Le:FN Ki:MS Pr:PI Wr:DR Ss:MJ Cy:WL Bn:SR H...,4489974.0:6065548.0:5406064.0:6364588.0:578832...,7727.0,BR Mt:JM Ve:TE At:JJ Wy:RA Wy:JK Fr:BC Hl:LA D...,4223883.0:2076192.0:8822729.0:5241564.0:202033...,2024-02-25 06:12:58
1435,9433703,Bm Bs,We,normal,Bm Bs,runs,53,NaN,We,field,...,175,9,120,10366.0,RM Ys:AL Ds:GJ Ml:DR My:CG Bn:JG Bl:CR Ws:EG B...,7681869.0:3612286.0:2275195.0:8210789.0:804411...,10576.0,BL Da:JA Hs:MJ Sr:AJ He:Kf Ai:OB Cx:Ua Mr:EJ P...,3298427.0:7773338.0:3519011.0:3681957.0:767131...,2024-02-25 06:12:58
1436,9433724,Sx,Gn,normal,Sx,runs,20,NaN,Sx,bat,...,162,8,120,9967.0,HD Wd:TR Ck:OJ Cr:RS Ba:Sb Kn:MK Bs:JM Cs:FJ H...,6311612.0:7753017.0:8015734.0:74087.0:6460614....,7573.0,KS Cn:SA Nt:WT Se:CD Fr:CB Ce:T vn dr Gn:AG Sr...,5164844.0:1722048.0:8110185.0:3834361.0:270743...,2024-02-25 06:12:58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
515,8887598,Be Ht,Ae Ss,normal,Be Ht,runs,39,BM Dt,Be Ht,bat,...,169,8,120,33921.0,CA Ln:M Bt:TW Cr:BM Dt:SD Ht:JJ Pn:JJ By:MT Se...,2286472.0:7620269.0:1539208.0:3651472.0:578676...,33914.0,J Wd:MW St:MT Rw:JW Ws:T Ky:HJ Nn:GS Gn:Rd Kn:...,5469008.0:4239038.0:5056134.0:1635773.0:841585...,2022-02-18 03:12:45
516,8887605,Ht Hs,Me Ss,normal,Ht Hs,runs,24,NT Es,Ht Hs,bat,...,151,9,120,33928.0,BR Mt:MS We:DM St:PP Hb:TH Dd:HC Bk:JA Tn:NT E...,4223883.0:1611364.0:2161599.0:2340372.0:624925...,33949.0,MP Ss:JM Ce:GJ Ml:JA Bs:AD Rl:HR Ct:BJ Wr:NM C...,2275097.0:4003390.0:2275195.0:2286437.0:193409...,2022-02-18 03:12:45
520,8887633,Me Ss,Be Ht,normal,Me Ss,runs,20,JM Ce,Be Ht,field,...,187,9,120,33949.0,MP Ss:JM Ce:JA Bs:GJ Ml:HR Ct:AD Rl:BJ Wr:NM C...,2275097.0:4003390.0:2286437.0:2275195.0:390107...,33921.0,M Bt:CA Ln:TW Cr:BM Dt:SD Ht:JJ Pn:JJ By:MT Se...,7620269.0:2286472.0:1539208.0:3651472.0:578676...,2022-02-18 03:12:45
517,8887612,Sy Ss,Sy Tr,normal,Sy Ss,runs,30,DT Cn,Sy Tr,field,...,142,10,93,33956.0,JR Pe:JM Ve:DP Hs:MC Hs:JC Sk:DT Cn:SA At:H Kr...,7869987.0:2076192.0:4002340.0:41740.0:3063696....,33963.0,M Gs:AD Hs:JS Sa:SW Bs:AI Rs:DR Ss:BJ Cg:N Mw:...,7572123.0:1749075.0:6718802.0:2083409.0:233538...,2022-02-18 03:12:45
519,8887626,Ae Ss,Ht Hs,normal,Ht Hs,wickets,7,BR Mt,Ae Ss,bat,...,176,3,117,33914.0,J Wd:MW St:MT Rw:JW Ws:T Ky:GS Gn:HJ Nn:Rd Kn:...,5469008.0:4239038.0:5056134.0:1635773.0:841585...,33928.0,BR Mt:MS We:DM St:HC Bk:TH Dd:PP Hb:JA Tn:NT E...,4223883.0:1611364.0:2161599.0:6381962.0:624925...,2022-02-18 03:12:45

In [32]:
batsman_df.columns

Index(['match id', 'batsman', 'batsman_id', 'batsman_dob', 'batsman_details',
       'is_batsman_captain', 'is_batsman_keeper', 'inning', 'runs',
       'balls_faced', 'over_faced_first', 'wicket kind', 'out_by_bowler',
       'out_by_fielder', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_keeper', 'is_bowler_captain', 'strike_rate', 'Fours',
       'Sixes', 'match_dt', 'ingestion_timestamp'],
      dtype='object')

In [33]:
bowlers_pd.columns

Index(['match id', 'bowler', 'bowler_id', 'bowler_dob', 'bowler_details',
       'is_bowler_captain', 'is_bowler_keeper', 'inning', 'runs',
       'wicket_count', 'balls_bowled', 'economy', 'maiden', 'dots', 'Fours',
       'Sixes', 'wides', 'noballs', 'match_dt', 'ingestion_timestamp'],
      dtype='object')

In [34]:
match_df.columns

Index(['match id', 'team1', 'team2', 'outcome', 'winner', 'by', 'win amount',
       'player of match', 'toss winner', 'toss decision', 'match type',
       'venue', 'city', 'match_dt', 'lighting', 'series_name', 'season',
       'ground_id', 'umpire1', 'umpire2', 'inning1_runs', 'inning1_wickets',
       'inning1_balls', 'inning2_runs', 'inning2_wickets', 'inning2_balls',
       'team1_id', 'team1_roster_names', 'team1_roster_ids', 'team2_id',
       'team2_roster_names', 'team2_roster_ids', 'ingestion_timestamp'],
      dtype='object')

Identify the batsman id and runs scored for the batsman who scored the highest runs in a match in 2022, but was never out for a duck ever.

In [35]:
batsman_df['match_dt'] = pd.to_datetime(batsman_df['match_dt'])
batsman_2022 = batsman_df[batsman_df['match_dt'].dt.year == 2022]

In [36]:
batsman_runs = batsman_df.groupby('batsman_id')['runs'].min().reset_index()
batsmen_never_duck = batsman_runs[batsman_runs['runs'] > 0]['batsman_id']

In [37]:
filtered_batsman_2022 = batsman_2022[batsman_2022['batsman_id'].isin(batsmen_never_duck)]

In [38]:
highest_scorer = filtered_batsman_2022.loc[filtered_batsman_2022['runs'].idxmax()]

In [39]:
batsman_id = highest_scorer['batsman_id']
runs_scored = highest_scorer['runs']

In [40]:
print(f"Batsman ID: {batsman_id}, Runs Scored: {runs_scored}")

Batsman ID: 3633503, Runs Scored: 100

Identify the bowler id, total no of wickets taken, and number of unique venues for the bowler who took wickets at maximum number of unique venues, given
the matches were won by their team by wickets.

In [41]:
import pandas as pd

# Assume match_df and bowler_df are preprocessed and already available
match_details = match_df
bowler_details = bowler_df

# Filter matches that were won by the team by wickets
won_by_wickets = match_details[match_details['by'] == 'wickets']

# Merge the filtered match details with bowler details on 'match_id'
merged_data = pd.merge(won_by_wickets, bowler_details, on='match id', how='inner')

# Group by bowler ID and calculate total wickets and unique venues
bowler_stats = merged_data.groupby('bowler_id').agg({
    'wicket_count': 'sum',
    'venue': pd.Series.nunique
}).reset_index()

# Identify the bowler with the maximum number of unique venues
top_bowler = bowler_stats.loc[bowler_stats['venue'].idxmax()]

# Output the required information
bowler_id = top_bowler['bowler_id']
total_wickets = top_bowler['wicket_count']
unique_venues = top_bowler['venue']

print(f"Bowler ID: {bowler_id}")
print(f"Total Wickets: {total_wickets}")
print(f"Number of Unique Venues: {unique_venues}")

Bowler ID: 2486896
Total Wickets: 36
Number of Unique Venues: 34

In [43]:
with pd.ExcelWriter('6655876402143_batsman_round1 (3).xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    batsman_df.to_excel(writer, sheet_name='Sheet1', index=False)

In [44]:
with pd.ExcelWriter('6655876ef0ec2_bowler_round1 (3).xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    bowler_df.to_excel(writer, sheet_name='Sheet1', index=False)

In [45]:
match_df.isnull().sum()

match id                 0
team1                    0
team2                    0
outcome                  0
winner                   0
by                      50
win amount               0
player of match        469
toss winner              0
toss decision            0
match type               0
venue                    0
city                   178
match_dt                 0
lighting                 0
series_name              0
season                   0
ground_id                0
umpire1                181
umpire2                181
inning1_runs             0
inning1_wickets          0
inning1_balls            0
inning2_runs             0
inning2_wickets          0
inning2_balls            0
team1_id                81
team1_roster_names       0
team1_roster_ids        81
team2_id                75
team2_roster_names       0
team2_roster_ids        75
ingestion_timestamp      0
dtype: int64

In [46]:
import pandas as pd
# Function to fill null values in the 'by' column
def fill_by_column(row):
    if pd.isnull(row['by']):
        if row['inning1_runs'] > row['inning2_runs']:
            return 'runs'
        else:
            return 'wickets'
    else:
        return row['by']

# Apply the function to each row in the DataFrame
match_df['by'] = match_df.apply(fill_by_column, axis=1)

In [47]:
match_df.isnull().sum()

match id                 0
team1                    0
team2                    0
outcome                  0
winner                   0
by                       0
win amount               0
player of match        469
toss winner              0
toss decision            0
match type               0
venue                    0
city                   178
match_dt                 0
lighting                 0
series_name              0
season                   0
ground_id                0
umpire1                181
umpire2                181
inning1_runs             0
inning1_wickets          0
inning1_balls            0
inning2_runs             0
inning2_wickets          0
inning2_balls            0
team1_id                81
team1_roster_names       0
team1_roster_ids        81
team2_id                75
team2_roster_names       0
team2_roster_ids        75
ingestion_timestamp      0
dtype: int64

In [48]:
with pd.ExcelWriter('6655877834f04_matchlevel_round1 (3).xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    match_df.to_excel(writer, sheet_name='Sheet1', index=False)

In [49]:
batsman_df.isnull().sum()

match id                   0
batsman                    0
batsman_id                 0
batsman_dob                0
batsman_details            0
is_batsman_captain         0
is_batsman_keeper          0
inning                     0
runs                       0
balls_faced                0
over_faced_first           0
wicket kind             5462
out_by_bowler           5462
out_by_fielder             6
bowler_id               6508
bowler_dob              6508
bowler_details          6508
is_bowler_keeper        5923
is_bowler_captain       6508
strike_rate                0
Fours                  10524
Sixes                  15719
match_dt                   0
ingestion_timestamp        0
dtype: int64

In [50]:
bowler_df.isnull().sum()

match id                0
bowler                  0
bowler_id               0
bowler_dob              0
bowler_details          0
is_bowler_captain       0
is_bowler_keeper        0
inning                  0
runs                    0
wicket_count            0
balls_bowled            0
economy                 0
maiden                  0
dots                    2
Fours                   0
Sixes                   0
wides                  34
noballs                 0
match_dt                0
ingestion_timestamp     0
dtype: int64

In [51]:
bowler_df['noballs'] = bowler_df['noballs'].apply(lambda x: max(x, 0))
bowler_df['noballs'].min()

0

In [52]:
with pd.ExcelWriter('6655876ef0ec2_bowler_round1 (3).xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    bowler_df.to_excel(writer, sheet_name='Sheet1', index=False)

In [53]:
bowler_df['wides'] = pd.to_numeric(bowler_df['wides'], errors='coerce')
bowler_df['wides'] = bowler_df['wides'].round().astype('Int64')

In [56]:
bowler_df['wides'].head(10)

7028     0
11413    2
8543     0
16473    0
10038    1
10039    0
10040    0
10041    1
10042    0
9455     0
Name: wides, dtype: Int64

In [57]:
text_to_num = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5,
    "Six": 6,
    "Seven": 7,
    "Eight": 8,
    "Nine": 9,
    "Ten": 10
    # Add more mappings if necessary
}

# Function to replace text with numeric values
def replace_text_with_num(value):
    if value in text_to_num:
        return text_to_num[value]
    return value

# Apply the function to the 'wides' column
bowler_df['wides'] = bowler_df['wides'].apply(replace_text_with_num)

# Convert the column to numeric, coercing errors (for any remaining non-numeric values)
bowler_df['wides'] = pd.to_numeric(bowler_df['wides'], errors='coerce')
bowler_df['wides'].fillna(0, inplace=True)
bowler_df['wides'] = bowler_df['wides'].round().astype('Int64')
# Replace NaN values that result from coercion with 0 (optional, depending on your requirements)

In [58]:
with pd.ExcelWriter('6655876ef0ec2_bowler_round1 (3).xlsx', engine='openpyxl', mode='a', if_sheet_exists='replace') as writer:
    bowler_df.to_excel(writer, sheet_name='Sheet1', index=False)